services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: faith
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: voicenote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance 
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - POSTGRESQL_URL=postgresql://faith:ECsNdJOe4eW3mB025O3CPlvLe76RQTLd@dpg-d76hjjbuibrs73bl11q0-a.oregon-postgres.render.com/voicenote_db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env

volumes:
  postgres_data: