"""Add more columns

Revision ID: 022c5e2548a2
Revises: cb5788a140c1
Create Date: 2026-03-30 10:55:57.918459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c5e2548a2'
down_revision = 'cb5788a140c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_transcript', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('key_decisions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('speaker_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meeting_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('meeting_metadata')
        batch_op.drop_column('speaker_count')
        batch_op.drop_column('key_decisions')
        batch_op.drop_column('action_items')
        batch_op.drop_column('structured_transcript')

    # ### end Alembic commands ###
